<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('AppBundle\\Controller\\UserCRUDController:indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.wytllxt']) ? $this->services['service_locator.wytllxt'] : $this->load(__DIR__.'/getServiceLocator_WytllxtService.php')) && false ?: '_'};
}, 'AppBundle\\Controller\\UserCRUDController::indexAction' => function () {
    return ${($_ = isset($this->services['service_locator.wytllxt']) ? $this->services['service_locator.wytllxt'] : $this->load(__DIR__.'/getServiceLocator_WytllxtService.php')) && false ?: '_'};
})));
