<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Form\Extension\ImageTypeExtension' shared autowired service.

return $this->services['App\Form\Extension\ImageTypeExtension'] = new \App\Form\Extension\ImageTypeExtension();
