<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sonata.admin.route_loader' shared service.

return $this->services['sonata.admin.route_loader'] = new \Sonata\AdminBundle\Route\AdminPoolLoader(${($_ = isset($this->services['sonata.admin.pool']) ? $this->services['sonata.admin.pool'] : $this->getSonata_Admin_PoolService()) && false ?: '_'}, array(0 => 'admin.category', 1 => 'admin.blog_post', 2 => 'admin.client', 3 => 'admin.support', 4 => 'admin.parfum', 5 => 'admin.user', 6 => 'admin.produit', 7 => 'admin.categories', 8 => 'admin.medias', 9 => 'admin.avis', 10 => 'admin.personalisation'), $this);
