services:
#    panier.example:
#        class: MSF\PanierBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
parameters:
#    panier.example.class: MSF\PanierBundle\Example