<?php

namespace AppBundle\Repository;

/**
 * LignedeCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignedeCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
