<?php

namespace AppBundle\Repository;

/**
 * ParfumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParfumRepository extends \Doctrine\ORM\EntityRepository
{
}
