imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    #upload path
    brochures_directory: '/uploads/brochures'
    media_directory: '/uploads/media'

framework:
    #esi: ~
    translator: { fallbacks: [fr] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# FOS Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: MyScentFactory\UserBundle\Entity\User
    from_email:
        address: "myscentfactory.admin@parkercommunication.pro
"
        sender_name: "MSF_team"

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'forms/fieldsTheme1.html.twig'
        - 'forms/fieldsTheme2.html.twig'
        - 'forms/fieldsTheme3.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'~
        #types:
            #json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # USE IF automapping false
        #entity_managers:
        #    default:
         #       mappings:
         #           SonataMediaBundle: ~

#Configuration sonata_media

#sonata_media:
#         #class:
#         #    media:   Sonata\MediaBundle\Entity\Media
#         #    gallery: Sonata\MediaBundle\Entity\Gallery
#         #    gallery_has_media: Sonata\MediaBundle\Entity\GalleryHasMedia

#         db_driver: doctrine_orm
#         default_context: default
#         contexts:
#             default:
#                 providers:
#                     - sonata.media.provider.image
#                     - sonata.media.provider.youtube
#                     - sonata.media.provider.file
#                     - sonata.media.resizer.square

#                 formats:
#                     small: { width: 100 , quality: 70}
#                     big:   { width: 500 , quality: 70}
#                     admin: { width: 300 , quality: 70}

#         cdn:
#             server:
#                 path: '%kernel.project_dir%/img/products'
#         filesystem:
#             local:
#                 directory: '%kernel.project_dir%/public/uploads/media'
#                 create: false


#vich Loader configuration using ORM engine
vich_uploader:
    db_driver: orm

#chargement depuis l'admin
    mappings:
        product_image:
            uri_prefix: /img
            upload_destination: '%kernel.project_dir%/img'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true



# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

sonata_block:
    default_contexts: [] # this line can be removed for sonata-project/block-bundle >= 3.10.0
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.stats:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]


#vu sonata
sonata_admin:
    title: MYSCENTFACTORY
    templates:
        layout: '@AppBundle/Resources/SonataTemplates/views/standard_layout.html.twig'
        dashboard: '@AppBundle/Resources/SonataTemplates/views/core/dashboard.html.twig'



    ###############CUSTOM KNP MENU LATER
     #   groups:
     #         client:
     #             label: ~
     #             label_catalogue: ~
     #             items:
     #                 - sonata.client.admin.post
     #                 - route:        client
     #                   label:        client_home
     #         news:
     #             label:    ~
     #             label_catalogue:    ~
     #             items:
     #                 - sonata.news.admin.post
     #                 - route:        blog_home
     #                   label:        Blog

        #knp_menu_template: "@AppBundle/Menu/custom_menu.html.twig"
            #groups:
                #news:
                   # label:    ~
                    #label_catalogue:    ~
               # items:
                    #- route:        blog_article
                    #  route_params: {articleId: 3}
                    #  label:        Article
                #roles: [ ROLE_ADMIN, ROLE_SUPER_ADMIN]
                #admin:
                #label:    ~
                #label_catalogue:    ~
                 # items:
                 #- sonata.news.admin.news


   ###############CUSTOM KNP MENU LATER###################################



sonata_doctrine_orm_admin:
    templates:
        form:
            - "@SonataDoctrineORMAdmin/Form/form_admin_fields.html.twig"
        filter:
            - "@SonataDoctrineORMAdmin/Form/filter_admin_fields.html.twig"
        types:
            list:
                array:      "@SonataAdmin/CRUD/list_array.html.twig"
                boolean:    "@SonataAdmin/CRUD/list_boolean.html.twig"
                date:       "@SonataAdmin/CRUD/list_date.html.twig"
                time:       "@SonataAdmin/CRUD/list_time.html.twig"
                datetime:   "@SonataAdmin/CRUD/list_datetime.html.twig"
                text:       "@SonataAdmin/CRUD/base_list_field.html.twig"
                trans:      "@SonataAdmin/CRUD/list_trans.html.twig"
                string:     "@SonataAdmin/CRUD/base_list_field.html.twig"
                smallint:   "@SonataAdmin/CRUD/base_list_field.html.twig"
                bigint:     "@SonataAdmin/CRUD/base_list_field.html.twig"
                integer:    "@SonataAdmin/CRUD/base_list_field.html.twig"
                decimal:    "@SonataAdmin/CRUD/base_list_field.html.twig"
                identifier: "@SonataAdmin/CRUD/base_list_field.html.twig"

            show:
                array:      "@SonataAdmin/CRUD/show_array.html.twig"
                boolean:    "@SonataAdmin/CRUD/show_boolean.html.twig"
                date:       "@SonataAdmin/CRUD/show_date.html.twig"
                time:       "@SonataAdmin/CRUD/show_time.html.twig"
                datetime:   "@SonataAdmin/CRUD/show_datetime.html.twig"
                text:       "@SonataAdmin/CRUD/base_show_field.html.twig"
                trans:      "@SonataAdmin/CRUD/show_trans.html.twig"
                string:     "@SonataAdmin/CRUD/base_show_field.html.twig"
                smallint:   "@SonataAdmin/CRUD/base_show_field.html.twig"
                bigint:     "@SonataAdmin/CRUD/base_show_field.html.twig"
                integer:    "@SonataAdmin/CRUD/base_show_field.html.twig"
                decimal:    "@SonataAdmin/CRUD/base_show_field.html.twig"
