admin_image:
    resource: "@AdminImageBundle/Resources/config/routing.yml"
    prefix:   /

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix:   /media/gallery

media:
    resource:  '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
panier:
    resource: "@PanierBundle/Controller/"
    type:     annotation
    prefix:   /commande

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

factory:
    resource: "@FactoryBundle/Controller/"
    type:     annotation
    prefix:   /factory

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /eshop


app:
    resource: '@AppBundle/Controller/'
    type: annotation
