fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_logout:
    path: /logout
    defaults: {_controller: FOSUserBundle:Security:logout, _method: POST}

fos_user_security_login:
    path: /login
    defaults: {_controller: FOSUserBundle:Security:login, _method: POST}

fos_user_registered_login:
    path: /user/relogin
    defaults: {_controller: UserBundle:RegisteredSecurity:login, _method: POST}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user/profile

espace_client:
    resource: "@UserBundle/Controller/"
    type: annotation
    prefix: /espace_client



