MSFBundle\Entity\image:

    type: entity
    repositoryClass: MSFBundle\Repository\ImageRepository
    table: images
    id:
        id:
            type: integer
            generator: {strategy: AUTO}

    fields:
        filename:
            type: string
            length: 255
        updated:
            type: datetime
            nullable: true
        imageAlt:
            type: text
            nullable: true

    lifecycleCallbacks:
        prePersist:    [lifecycleFileUpload]
        preUpdate:     [lifecycleFileUpload]