#crud ecommerce

media_annotation_route:
    resource: "@EcommerceBundle/Controller/MediaController.php"
    type: annotation

categorie_annotation_route:
    resource: "@EcommerceBundle/Controller/CategoriesController.php"
    type: annotation

produit_annotation_route:
    resource: "@EcommerceBundle/Controller/ProduitsController.php"
    type: annotation

panier_annotation_route:
    resource: "@EcommerceBundle/Controller/PanierController.php"
    type: annotation

tva_annotation_route:
    resource: "@EcommerceBundle/Controller/TVAController.php"
    type: annotation

bondecommande_annotation_route:
    resource: "@EcommerceBundle/Controller/CommandeController.php"
    type: annotation

