ecommerce_homepage:
    path:     /
    defaults: { _controller: EcommerceBundle:Default:index }

panier:
    path:     /panier
    defaults: { _controller: EcommerceBundle:Panier:panier }

livraison:
    path:     /livraison
    defaults: { _controller: EcommerceBundle:Panier:livraison }

validation:
    path:     /validation
    defaults: { _controller: EcommerceBundle:Panier:validation }

catalogue_produits:
    path:     /produits
    defaults: { _controller: EcommerceBundle:Produits:produits }

presentation:
    path:     /presentation
    defaults: { _controller: EcommerceBundle:Produits:presentation }

composition_client:
    path:     /composition
    defaults: { _controller: EcommerceBundle:Produits:composition }

ajout_produit:
    path: /ajoutProduit
    defaults: { _controller: EcommerceBundle:Produits:add }

modifier_produit:
    path: /modifierProduit
    defaults: { _controller: EcommerceBundle:Produits:modifier }

editer_produit:
    path: /editer/{id}
    defaults: { _controller: EcommerceBundle:Produits:update}


#crud ecommerce

media_annotation_route:
    resource: "@EcommerceBundle/Controller/MediaController.php"
    type: annotation

produit_annotation_route:
    resource: "@EcommerceBundle/Controller/ProduitsController.php"
    type: annotation

categorie_annotation_route:
    resource: "@EcommerceBundle/Controller/CategoriesController.php"
    type: annotation

tva_annotation_route:
    resource: "@EcommerceBundle/Controller/TVAController.php"
    type: annotation

panier_annotation_route:
    resource: "@EcommerceBundle/Controller/PanierController.php"
    type: annotation