<?php

namespace MSFBundle\Repository;

use Doctrine\ORM\QueryBuilder;
use MyScentFactory\MSFBundle\Entity\Image;
use Symfony\Bridge\Doctrine\RegistryInterface;
/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function imageList()
    {
       $this->getDoctrine()->getRepository(Image::class);

// createQueryBuilder() automatically selects FROM AppBundle:Product
// and aliases it to "p"
        $query = $repository->createQueryBuilder('p')
            ->where('p.price > :price')
            ->setParameter('price', '19.99')
            ->orderBy('p.price', 'ASC')
            ->getQuery();

        $products = $query->getResult();
// to get just one result:
// $product = $query->setMaxResults(1)->getOneOrNullResult();
    }
}
