<?php

namespace MyScentFactory\MSFBundle\Repository;

/**
 * MediaUploadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaUploadsRepository extends \Doctrine\ORM\EntityRepository
{
}
