<?php

namespace MSFBundle\Repository;


/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM MSFBundle:Photo p ORDER BY p.photo ASC'
            )
            ->getResult();
    }
}
