<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'application_fos_user.security.interactive_login_listener' shared autowired service.

return $this->services['application_fos_user.security.interactive_login_listener'] = new \MyScentFactory\UserBundle\EventListener\UserListener();
