<?php

namespace MSF\EcommerceBundle\Repository;

/**
 * AmbianceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmbianceRepository extends \Doctrine\ORM\EntityRepository
{
}
