<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD3qnkhp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD3qnkhp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerD3qnkhp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerD3qnkhp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerD3qnkhp\appDevDebugProjectContainer(array(
    'container.build_hash' => 'D3qnkhp',
    'container.build_id' => '6589874f',
    'container.build_time' => 1519059156,
));
